# HTTP Log Monitor Configuration Options
highTrafficAlert:
  threshold: 10
  sampleWindow: 120
  enabled: true
stats:
  printInterval: 10
  enabled: true
path:
  file:
  stdin:

eventBuffer:
  size: 16


# Spring configuration
spring:
  main:
    web-application-type: none